### ISSUE TITLE
Usar fmt.Printf em vez de fmt.Println

### ISSUE THREAD

**Issue by canhizares** [gaviusking/Go4Noobs#3]
Tem vários exemples que talvez fiquem mais legivéis utilizando o [fmt.Printf](https://golang.org/pkg/fmt/#Printf)

Por exemplo:
```golang
fmt.Println(name, "de", age, "anos possui exatos R$", balance, "em sua conta!")
```
Que podería ser usado como usando o fmt.Printf da seguinte maneira:

```golang
fmt.Printf("%s de %d anos possui exatos R$ %0.2f em sua conta!\n", name, age, balance)
```

Eu acho que assim fica um código mais legível mas não fiz um PR porque talvez você prefira usar sempre a outra opção.

**Comment by caioreix** [comment]
Então Matheus, eu até pensei em fazer com o Printf, mas a sintaxe da formatação não é tão amigável para quem ainda não a viu anteriormente em C/C++ etc. Então optei por manter apenas o Println até o momento. Uma possível mudança que eu talvez faça futuramente é traduzir as variáveis e as funções.

**Comment by canhizares** [comment]
Entendo, por isso perguntei antes. 

Mas também sería legal o pessoal começar vendo o Printf porque em muitos exemplos com textos e manipulação de textos mas isso também podería ir em um seção diferente da documentação para poder explicar também os modificadores usando o `%`.

Sobre as traduções, os nomes de funções e variavéis são básicos então não vejo muito problema, mas é certo que estando toda a doc em português, pode ser uma boa.
