### ISSUE TITLE
Criar índice novo para Tipo de datos.

### ISSUE THREAD

**Issue by canhizares** [gaviusking/Go4Noobs#4]
Olhando a documentação acho que sería legal mover os seguintes apartados em um índice novo que sería tipo de datos e aproveitar para explicar um pouco mais em detalhe os diferentes tipos de datos básicos e também os compostos (map, array, slice...)

[Tipos básicos de variavéis](https://github.com/caioreix/go4noobs/blob/master/modules/basico.md#tipos-b%C3%A1sicos-de-vari%C3%A1veis)

[Variavéis com valor 0](https://github.com/caioreix/go4noobs/blob/master/modules/basico.md#vari%C3%A1veis-com-valores-zero)

Se estiver de acordo eu mesmo posso mudar e adicionar informação sobre esses tipos básicos.

**Comment by caioreix** [comment]
Penso que seria muito bom, estou querendo mudar a estrutura do repositório, mas no momento não estou com muito tempo livre.
Se preferir pode estruturar no índice do roadmap dessa forma:
## ROADMAP

### Introdução

- [Introdução]()
- [Instalação]()

### Estrutura de dados

- [Tipos de dados]()

Em minha opinião assim é uma boa forma de organizar o repositório, mas sinta-se a vontade em apresentar de outra forma.

**Comment by caioreix** [comment]
@canhizares Atualizei a estrutura do README.md. Quando for adicionar os tópicos adiciona entre a introdução e os resumos por favor.

**Comment by canhizares** [comment]
@caioreix  Ta bom, adicionarei ai então. 

Tem como você colocar eu como asignee dessa issue aqui?
